POST http://localhost:9090/file
Accept: */*
Content-Type: multipart/form-data; boundary=boundary
Authorization: local_api_key

--boundary
Content-Disposition: form-data; name="file"; filename="file1.csv"
Content-Type: text/csv

< ./file1.csv
--boundary--
